import { useMemo } from "react";
import { TeamMemberRowData } from "@/types";

const useMockTeamMemberData = () => {
  const mockData: TeamMemberRowData[] = useMemo(
    () => [
      {
        id: 1,
        name: "Henry Masovid",
        email: "henrymaso@example.com",
        location: "Lagos",
        startDate: "Jun 12, 2024",
        jobTitle: "Software Engineer",
        phoneNumber: "+234 9135669877",
        status: "Active",
      },
      {
        id: 2,
        name: "Jane Doe",
        email: "jane@example.com",
        location: "Lagos",
        startDate: "Mar 20, 2023",
        jobTitle: "Product Manager",
        phoneNumber: "+234 9135669878",
        status: "On Leave",
      },
      {
        id: 3,
        name: "John Smith",
        email: "john@example.com",
        location: "Abuja",
        startDate: "May 10, 2022",
        jobTitle: "UX Designer",
        phoneNumber: "+234 9135669879",
        status: "Active",
      },
      {
        id: 4,
        name: "Alice Johnson",
        email: "alice@example.com",
        location: "Lagos",
        startDate: "Jul 22, 2021",
        jobTitle: "Marketing Specialist",
        phoneNumber: "+234 9135669880",
        status: "Offline",
      },
      {
        id: 5,
        name: "Robert Brown",
        email: "henrymasostretch@example.com",
        location: "Port Harcourt",
        startDate: "Feb 18, 2023",
        jobTitle: "Data Analyst",
        phoneNumber: "+234 9135669881",
        status: "Active",
      },
      {
        id: 6,
        name: "Emily White",
        email: "emily@example.com",
        location: "Ibadan",
        startDate: "Nov 01, 2023",
        jobTitle: "Sales Executive",
        phoneNumber: "+234 9135669882",
        status: "On Leave",
      },
      {
        id: 7,
        name: "Michael Black",
        email: "michael@example.com",
        location: "Kano",
        startDate: "Sep 05, 2021",
        jobTitle: "System Administrator",
        phoneNumber: "+234 9135669883",
        status: "Active",
      },
      {
        id: 8,
        name: "Sophia Grey",
        email: "sophia@example.com",
        location: "Lagos",
        startDate: "Apr 14, 2023",
        jobTitle: "Content Writer",
        phoneNumber: "+234 9135669884",
        status: "Offline",
      },
      {
        id: 9,
        name: "James Blue",
        email: "james@example.com",
        location: "Abuja",
        startDate: "Dec 09, 2020",
        jobTitle: "HR Manager",
        phoneNumber: "+234 9135669885",
        status: "Active",
      },
      {
        id: 10,
        name: "Liam Red",
        email: "liam@example.com",
        location: "Lagos",
        startDate: "Jan 20, 2021",
        jobTitle: "DevOps Engineer",
        phoneNumber: "+234 9135669886",
        status: "On Leave",
      },
      {
        id: 11,
        name: "Olivia Green",
        email: "olivia@example.com",
        location: "Enugu",
        startDate: "May 15, 2023",
        jobTitle: "Front-End Developer",
        phoneNumber: "+234 9135669887",
        status: "Active",
      },
      {
        id: 12,
        name: "Isabella Yellow",
        email: "isabella@example.com",
        location: "Kano",
        startDate: "Oct 12, 2022",
        jobTitle: "Back-End Developer",
        phoneNumber: "+234 9135669888",
        status: "Offline",
      },
    ],
    [],
  );

  return mockData;
};

export default useMockTeamMemberData;
